#!/bin/bash

sudo xbps-install -Sy       \
        python              \
        python-pip          \
        python3             \
        python3-pip         \
        ninja               \
        gettext             \
        libtool             \
        libltdl             \
        autoconf            \
        automake            \
        cmake               \
        gcc                 \
        gcc6                \
        pkg-config          \
        unzip               \
        libX11-devel        \
        libXext-devel       \
        tmux                \
        zsh                 \
        curl                \
        wget                \
        git                 \
        nodejs              \
        ripgrep             \
        the_silver_searcher \
        StyLua              \
        bat                 \
        clang               \
        docx2txt            \
        exa                 \
        exfat-utils         \
        fd                  \
        fish-shell          \
        gdb                 \
        glade3              \
        glade3-devel        \
        go                  \
        htop                \
        libreoffice-calc    \
        llvm-12.0.0_1       \
        meson               \
        rsync               \
        stow                \
        sxhkd               \
        tlp                 \
        void-repo-nonfree   \
        xauth               \
        xclip               \
        xdo                 \
        xinit               \
        xrandr              \
        xsetroot            \
        xtools              \
        MEGAcmd             \
        tectonic            \
        zathura             \
        xdo                 \
        fzf                 \
        zathura-pdf-mupdf   \
        ffmpeg              \
        sxiv                \
        xorg-util-macros    \
        intel-ucode         \
        xf86-video-intel    \
        intel-ucode         \
        mesa-vulkan-intel   \
        mesa-intel-dri      \
        libva-intel-driver  \
        intel-video-accel   \
        intel-undervolt     \
        intel-media-driver  \
        acpica-utils        \
        intel-gmmlib        \
        intel-gmmlib-devel  \
        kitty               \
        wpa_supplicant      \
